# Generated by Django 5.2.7 on 2025-11-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
